### ISSUE TITLE
可以支持搜索过滤完整的数据吗？

### ISSUE THREAD

**Issue by guxiang02** [xiaocheng555/a-virtual-table#1]
目前过滤的数据不是全量的，只能过滤可视区域内的数据

**Comment by xiaocheng555** [comment]
> 目前过滤的数据不是全量的，只能过滤可视区域内的数据

组件不支持过滤，可以自己在组件外面写搜索过滤的逻辑

**Comment by xiaocheng555** [comment]
我有空写个demo

**Comment by xiaocheng555** [comment]
> 目前过滤的数据不是全量的，只能过滤可视区域内的数据

增加筛选、搜索demo： https://xiaocheng555.github.io/a-virtual-table/#/Filter?code=Filter&codeTitle=%E6%90%9C%E7%B4%A2%26%E7%AD%9B%E9%80%89
