### ISSUE TITLE
demo 的搜索筛选功能不可用

### ISSUE THREAD

**Issue by cooper1x** [xiaocheng555/a-virtual-table#10]
https://xiaocheng555.github.io/a-virtual-table/#/Filter?code=Filter&codeTitle=%E6%90%9C%E7%B4%A2%26%E7%AD%9B%E9%80%89

**Comment by xiaocheng555** [comment]
> https://xiaocheng555.github.io/a-virtual-table/#/Filter?code=Filter&codeTitle=%E6%90%9C%E7%B4%A2%26%E7%AD%9B%E9%80%89

已修复，升级到1.1.3
