### ISSUE TITLE
无法获取record 

### ISSUE THREAD

**Issue by hwd9061** [xiaocheng555/a-virtual-table#2]
slot-scope="text”  只能获取到 text   ,无法获取record   我的操作列都无法使用了

**Comment by hwd9061** [comment]
<span slot="action" slot-scope="text, record"  v-if="canEdit">
         
          <a-popconfirm title="确定删除吗?" @confirm="() => handleDelete(record.id)">
            <a>删除</a>
          </a-popconfirm>
        </span>

**Comment by xiaocheng555** [comment]
> slot-scope="text” 只能获取到 text ,无法获取record 我的操作列都无法使用了

```
<a-virtual-table
      :columns="columns"
      :data-source="list"
      :itemSize="54"
      keyProp="id"
      row-key="id"
      :scroll="{ x: 1300, y: 600 }">
      <a slot="name" slot-scope="record">{{ record }}===</a>
    </a-virtual-table>

columns中不设置dateIndex，可以拿到record
columns: [
        {
          title: 'Name',
          key: 'name',
          scopedSlots: { customRender: 'name' },
          width: 200
        }
...
]
```

**Comment by hwd9061** [comment]
恢复好快   大神。我以为我没希望了

**Comment by xiaocheng555** [comment]
> 恢复好快 大神。我以为我没希望了

刚好看到😂
