### ISSUE TITLE
在列少情况下  网格列对不齐

### ISSUE THREAD

**Issue by hwd9061** [xiaocheng555/a-virtual-table#4]
在列少情况下。没有X滚动条。列就会对不齐
  <a-virtual-table
        rowKey="id"
        keyProp="id"
        :itemSize="54"
        bordered
        :scroll="{x:'1300' ,y: 500}"
        :columns="columns"
        :dataSource="dataSource"
        :loading="loading"
        :rowSelection="{selectedRowKeys: selectedRowKeys, onChange: onSelectChange}"
        >

 columns: [
          {
            title: '#',
            index: true,
            width:60,
          },
          {
            title:'唯一码',
            align:"center",
            dataIndex: 'prodUnicode',
            width:280,
            scopedSlots: {
              filterDropdown: 'filterProdUnicode'
            },
          },
          {
            title:'数量',
            align:"center",
            width:60,
            dataIndex: 'qty'
          },
          {
            title:'sku代码',
            align:"center",
            width:200,
            dataIndex: 'skuCode'
          },
          {
            title:'商品代码',
            align:"center",
            width:100,
            dataIndex: 'prodCode'
          },
          {
            title:'款号',
            align:"center",
            width:100,
            dataIndex: 'prodModel'
          },
          {
            title:'名称',
            align:"center",
            width:150,
            dataIndex: 'prodName'
          },
          {
            title:'属性',
            align:"center",
            width:250,
            dataIndex: 'skuValues'
          },

          {
            title: '操作',
            align:"center",
            fixed:"right",
            width:60,
            scopedSlots: { customRender: 'action' },
          }
        ]

**Comment by xiaocheng555** [comment]
> 在列少情况下。没有X滚动条。列就会对不齐
> 
> columns: [ { title: '#', index: true, width:60, }, { title:'唯一码', align:"center", dataIndex: 'prodUnicode', width:280, scopedSlots: { filterDropdown: 'filterProdUnicode' }, }, { title:'数量', align:"center", width:60, dataIndex: 'qty' }, { title:'sku代码', align:"center", width:200, dataIndex: 'skuCode' }, { title:'商品代码', align:"center", width:100, dataIndex: 'prodCode' }, { title:'款号', align:"center", width:100, dataIndex: 'prodModel' }, { title:'名称', align:"center", width:150, dataIndex: 'prodName' }, { title:'属性', align:"center", width:250, dataIndex: 'skuValues' },
> 
> ```
>       {
>         title: '操作',
>         align:"center",
>         fixed:"right",
>         width:60,
>         scopedSlots: { customRender: 'action' },
>       }
>     ]
> ```

有图吗

**Comment by hwd9061** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xiaocheng555/a-virtual-table"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月23日(星期天) 中午11:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xiaocheng555/a-virtual-table] 在列少情况下  网格列对不齐 (Issue #4)





  
在列少情况下。没有X滚动条。列就会对不齐
 
columns: [ { title: '#', index: true, width:60, }, { title:'唯一码', align:"center", dataIndex: 'prodUnicode', width:280, scopedSlots: { filterDropdown: 'filterProdUnicode' }, }, { title:'数量', align:"center", width:60, dataIndex: 'qty' }, { title:'sku代码', align:"center", width:200, dataIndex: 'skuCode' }, { title:'商品代码', align:"center", width:100, dataIndex: 'prodCode' }, { title:'款号', align:"center", width:100, dataIndex: 'prodModel' }, { title:'名称', align:"center", width:150, dataIndex: 'prodName' }, { title:'属性', align:"center", width:250, dataIndex: 'skuValues' },
       {         title: '操作',         align:"center",         fixed:"right",         width:60,         scopedSlots: { customRender: 'action' },       }     ]   
有图吗
 
—

无数据情况









有数据情况






我的网格设置



在宽度小 或者列宽或者数量 大于我显示区域宽度时候&nbsp; 有滚动条就不会有问题。

**Comment by hwd9061** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xiaocheng555/a-virtual-table"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月23日(星期天) 中午11:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xiaocheng555/a-virtual-table] 在列少情况下  网格列对不齐 (Issue #4)





  
在列少情况下。没有X滚动条。列就会对不齐
 
columns: [ { title: '#', index: true, width:60, }, { title:'唯一码', align:"center", dataIndex: 'prodUnicode', width:280, scopedSlots: { filterDropdown: 'filterProdUnicode' }, }, { title:'数量', align:"center", width:60, dataIndex: 'qty' }, { title:'sku代码', align:"center", width:200, dataIndex: 'skuCode' }, { title:'商品代码', align:"center", width:100, dataIndex: 'prodCode' }, { title:'款号', align:"center", width:100, dataIndex: 'prodModel' }, { title:'名称', align:"center", width:150, dataIndex: 'prodName' }, { title:'属性', align:"center", width:250, dataIndex: 'skuValues' },
       {         title: '操作',         align:"center",         fixed:"right",         width:60,         scopedSlots: { customRender: 'action' },       }     ]   
有图吗
 
—

但是我刚已经找到解决方案了。 改了一下 x='1300' 数字变成字符串&nbsp; 就解决了 。但是完全无法理解&nbsp; 其他暂时没问题了

**Comment by xiaocheng555** [comment]
设置x='1300' 数字变成字符串就相当于没有设置x，x不支持字符串，在没有x轴滚动时就可以不用设置x值了。
这个问题刚修复了，版本是1.0.8，你也可以升级一下试试

**Comment by xiaocheng555** [comment]
> 设置x='1300' 数字变成字符串就相当于没有设置x，x不支持字符串，在没有x轴滚动时就可以不用设置x值了。
> 这个问题刚修复了，版本是1.0.8，你也可以升级一下试试

设置x='1300' 数字变成字符串就相当于没有设置x，x不支持字符串，在没有x轴滚动时就可以不用设置x值了。
这个问题刚修复了，版本是1.0.8，你也可以升级一下试试

**Comment by hwd9061** [comment]
好的&nbsp; 我试下




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月23日(星期天) 中午12:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xiaocheng555/a-virtual-table] 在列少情况下  网格列对不齐 (Issue #4)





  
设置x='1300' 数字变成字符串就相当于没有设置x，x不支持字符串，在没有x轴滚动时就可以不用设置x值了。
 这个问题刚修复了，版本是1.0.8，你也可以升级一下试试
  
设置x='1300' 数字变成字符串就相当于没有设置x，x不支持字符串，在没有x轴滚动时就可以不用设置x值了。
 这个问题刚修复了，版本是1.0.8，你也可以升级一下试试
