### ISSUE TITLE
自定义列表标题不会显示

### ISSUE THREAD

**Issue by rongbinxm** [xiaocheng555/a-virtual-table#5]
## 自定义列表标题，不会显示
``` vue
<a slot="name" slot-scope="text">{{ text }}</a>
<span slot="customTitle"><a-icon type="smile-o" /> Name</span>
```

``` js
columns = [
  {
    dataIndex: 'name',
    key: 'name',
    slots: { title: 'customTitle' },
    scopedSlots: { customRender: 'name' },
  }]
```

**Comment by xiaocheng555** [comment]
> ## 自定义列表标题，不会显示
> ```
> <a slot="name" slot-scope="text">{{ text }}</a>
> <span slot="customTitle"><a-icon type="smile-o" /> Name</span>
> ```
> 
> ```js
> columns = [
>   {
>     dataIndex: 'name',
>     key: 'name',
>     slots: { title: 'customTitle' },
>     scopedSlots: { customRender: 'name' },
>   }]
> ```

没考虑这个情况 我修复下

**Comment by xiaocheng555** [comment]
> ## 自定义列表标题，不会显示
> ```
> <a slot="name" slot-scope="text">{{ text }}</a>
> <span slot="customTitle"><a-icon type="smile-o" /> Name</span>
> ```
> 
> ```js
> columns = [
>   {
>     dataIndex: 'name',
>     key: 'name',
>     slots: { title: 'customTitle' },
>     scopedSlots: { customRender: 'name' },
>   }]
> ```

bug修复了, 升级版本到1.0.9
