### ISSUE TITLE
获取不了record index

### ISSUE THREAD

**Issue by 123303841** [xiaocheng555/a-virtual-table#7]
`      <template v-for="slot in Object.keys($scopedSlots)" :slot="slot" slot-scope="text">
<slot :name="slot" v-bind="typeof text === 'object' ? text : {text}"></slot>
      </template>     `
应该改成：
`
 <template v-for="slot in Object.keys($scopedSlots)" :slot="slot" slot-scope="text, record, index">
        <slot :name="slot" v-bind="{text, record, index}"></slot>
      </template>`

**Comment by xiaocheng555** [comment]
> ` <template v-for="slot in Object.keys($scopedSlots)" :slot="slot" slot-scope="text"> <slot :name="slot" v-bind="typeof text === 'object' ? text : {text}"></slot> </template> ` 应该改成： ` <template v-for="slot in Object.keys($scopedSlots)" :slot="slot" slot-scope="text, record, index"> <slot :name="slot" v-bind="{text, record, index}"></slot> </template>`

感谢感谢，已经修改了，发布到  a-virtual-table@1.0.10 版本
