### ISSUE TITLE
表格树如何修改

### ISSUE THREAD

**Issue by jiangzhikele** [xiaocheng555/a-virtual-table#8]
我现在有个需求，使用 antd 的 table， 但数据量太大了，所以也想用虚拟滚动效果，请问下有什么思路吗？样式和框架还是想使用 antd 的 css。

**Comment by xiaocheng555** [comment]
> 我现在有个需求，使用 antd 的 table， 但数据量太大了，所以也想用虚拟滚动效果，请问下有什么思路吗？样式和框架还是想使用 antd 的 css。

暂时没时间做支持，可以参考这个demo
https://github.com/xiaocheng555/el-table-virtual-scroll/blob/master/demo/src/views/TreeDemo2.vue

**Comment by xiaocheng555** [comment]
> 我现在有个需求，使用 antd 的 table， 但数据量太大了，所以也想用虚拟滚动效果，请问下有什么思路吗？样式和框架还是想使用 antd 的 css。

https://xiaocheng555.github.io/a-virtual-table/#/VTreeDemo?code=VTreeDemo&codeTitle=%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%91%E5%BD%A2%E7%BB%93%E6%9E%841

1.1.0 已支持表格树，参考上面demo

**Comment by xiaocheng555** [comment]
https://xiaocheng555.github.io/a-virtual-table/#/TreeDemo?code=TreeDemo&codeTitle=%E6%A0%91%E5%BD%A2%E7%BB%93%E6%9E%84

也可以使用原来表格树，只对第一层树结构做虚拟滚动，性能没那么好

**Comment by jiangzhikele** [comment]
非常感谢提供了帮助，我目前实现是把树形打成数组后，按照深度再定义每行的递进

**Comment by jiangzhikele** [comment]
我明天看你新的代码，非常感谢
